version: 2

jobs:
  test-node:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: make test-node

  test-ui:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: make prod
      - run: make start-test
      - run: make test-ui

  test-bot:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: make prod
      - run: make start-test
      - run: make test-bot

  push-latest-images:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make prod
      - run: make push-latest

  push-prod-images:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make prod
      - run: make push-prod

  deploy-staging:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          command: |
            ssh ubuntu@$STAGING_DOMAINNAME "bash -s" <<EOF
              set -e
              git clone https://github.com/ConnextProject/indra.git || true
              cd indra
              git checkout --force $CIRCLE_BRANCH
              git fetch
              git reset --hard $CIRCLE_SHA1
              export INDRA_MODE="staging"
              export INDRA_ETH_PROVIDER=$RINKEBY_ETH_PROVIDER
              export INDRA_PISA_URL=$RINKEBY_PISA_URL
              export INDRA_DOMAINNAME="$STAGING_DOMAINNAME"
              make restart-prod
              docker container prune -f
              docker image ls -q | xargs docker image rm || true
            EOF

  deploy-prod:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          command: |
            ssh ubuntu@$RINKEBY_DOMAINNAME "bash -s" <<EOF
              set -e
              git clone https://github.com/ConnextProject/indra.git || true
              cd indra
              git checkout --force $CIRCLE_BRANCH
              git fetch
              git reset --hard $CIRCLE_SHA1
              export INDRA_MODE="prod"
              export INDRA_ETH_PROVIDER=$RINKEBY_ETH_PROVIDER
              export INDRA_PISA_URL=$RINKEBY_PISA_URL
              export INDRA_DOMAINNAME="$RINKEBY_DOMAINNAME"
              make restart-prod
              docker container prune -f
              docker image ls -q | xargs docker image rm || true
            EOF
            ssh ubuntu@$MAINNET_DOMAINNAME "bash -s" <<EOF
              set -e
              git clone https://github.com/ConnextProject/indra.git || true
              cd indra
              git checkout --force $CIRCLE_BRANCH
              git fetch
              git reset --hard $CIRCLE_SHA1
              export INDRA_MODE="prod"
              export INDRA_ETH_PROVIDER=$MAINNET_ETH_PROVIDER
              export INDRA_PISA_URL=$MAINNET_PISA_URL
              export INDRA_DOMAINNAME="$MAINNET_DOMAINNAME"
              make restart-prod
              docker container prune -f
              docker image ls -q | xargs docker image rm || true
            EOF

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-node
      - test-ui
      - test-bot

      - push-latest-images:
          filters:
            branches:
              only: staging
          requires:
            - test-node
            - test-ui
            - test-bot

      - push-prod-images:
          filters:
            branches:
              only: master
          requires:
            - test-node
            - test-ui
            - test-bot

      - deploy-staging:
          requires:
            - push-latest-images

      - deploy-prod:
          requires:
            - push-prod-images
