name: CD Tests

on:
  push:
    branches-ignore:
      - master
      - staging

jobs:
  build:
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: .npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: make pull-latest
    - run: make staging
    - run: make build-report
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - run: make push-commit

  test-cf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make cf-core
    - run: make test-cf

  test-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: .npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: make client
    - run: make test-client

  test-contracts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: .npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: make contracts
    - run: make test-contracts

  test-node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: make node
    - run: make test-node

  test-integration:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v1
    - run: make pull-commit
    - run: make start-test-staging
    - run: sleep 15 && make dls
    - run: TEST_MODE=staging make test-integration || docker service logs --tail 1000 indra_node

  test-backwards-compatibility:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v1
    - run: make pull-commit
    - run: make start-test-staging
    - run: sleep 15 && make dls
    - run: make test-backwards-compatibility || docker service logs --tail 1000 indra_node

  test-daicard:
    runs-on: ubuntu-16.04
    needs: [build]
    steps:
    - uses: actions/checkout@v1
    - run: make pull-commit
    - run: make start-test-staging
    - run: make test-daicard || docker service logs --tail 1000 indra_node
