name: CI Tests

on:
  push:
    branches-ignore:
      - master
      - staging

jobs:
  test-cf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: .npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: make cf-core
    - run: make test-cf

  test-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: .npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: make client
    - run: make test-client

  test-contracts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: .npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: make contracts
    - run: make test-contracts

  test-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: .npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: make pull-latest
    - run: make
    - run: make start-headless
    - run: make build-report
    - run: sleep 15 && make dls
    - run: TEST_MODE=staging make test-integration
